version: '3.3'

services:
  api:
    container_name: capstone-api
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '8080'
    restart: always
  web:
    container_name: capstone-web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080'
    depends_on:
      - api
    volumes:
      - ./frontend/:/usr/src/frontend/
    restart: always
  nginx:
    container_name: capstone-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '8080'
    depends_on:
      - api
      - web
    restart: always
